### ISSUE TITLE
Fix socmed bugs

### ISSUE THREAD

**Issue by gremmyz** [AY2223S2-CS2103T-W15-1/tp#115]
**Updated command list:**
- [x] `add n/Jason tg/` - empty input does not return error message
- [x] `add n/Jason wa/` - empty input does not return error message
- [x] `add n/Jason ig/` - empty input does not return error message
- [x] `add n/Jason ig/jason.jason.jason.jason.jason.jason.jason` - IG name > 30 characters does not return error message

**Comment by salty-flower** [comment]
Noted, will do
