### ISSUE TITLE
[PE-D][Tester A] Command is case-sensitive

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W15-1/tp#175]
![3.png](https://raw.githubusercontent.com/Mr-Teal/ped/main/files/26251e79-dcde-40e2-ad5d-b618a6a89e2c.png)

![4.png](https://raw.githubusercontent.com/Mr-Teal/ped/main/files/f1fba8a1-948a-41b3-bcd8-e09bd795e8d4.png)

![5.png](https://raw.githubusercontent.com/Mr-Teal/ped/main/files/544e70a4-f1c9-48d1-a713-40cdc2ffc378.png)

Cannot enter the command 'AdD n/James' while the app supports 'add n/James'.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: Mr-Teal/ped#2

**Comment by gremmyz** [comment]
already specified in UG (section 3.3 command format)
