### ISSUE TITLE
[PE-D][Tester A] Phone number with + sign is not supported

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W15-1/tp#180]
![8.png](https://raw.githubusercontent.com/Mr-Teal/ped/main/files/f3104d30-d82a-45c5-a9f1-6912e55f0b1f.png)

![9.png](https://raw.githubusercontent.com/Mr-Teal/ped/main/files/3672765d-2222-49e3-b37a-8fa10d9c22c0.png)

Cannot have the phone number to include '+' sign(which is for indicating phone region number).

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: Mr-Teal/ped#4

**Comment by gremmyz** [comment]
i believe that "should only contain numbers" is clear enough that + cannot be used.
