### ISSUE TITLE
[PE-D][Tester E] Edit does not catch invalid date entered for Birthday

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-W15-1/tp#195]
A birthday is a day that someone was born, and to know a person, they would have to first be born.

Minor detail to note that the application allows invalid birthdates which are dated in the future

![image.png](https://raw.githubusercontent.com/joytqt-1202/ped/main/files/4e8916d3-3863-461e-ab51-9e2898d7a1b7.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: joytqt-1202/ped#6

**Comment by gremmyz** [comment]
duplicate #177
