### ISSUE TITLE
Hide optional label in output

### ISSUE THREAD

**Issue by vsamarth** [AY2223S2-CS2103T-W15-1/tp#225]
I am not sure if it's a cosmetic bug (but i feel like it's a functionality).
Adding a new person with let's say only name and phone still shows `Optional.empty` in the output.

Even where values (like phone no.) is present, it is wrapped around `Optional[]`

<img width="740" alt="Screenshot 2023-04-08 at 6 17 33 AM" src="https://user-images.githubusercontent.com/62458106/230685659-1cb89c2d-7f9a-42c9-a5a8-559637593998.png">

**Comment by vsamarth** [comment]
@salty-flower @Lava-Iris @gremmyz @Saha9616 any ideas?

I might try to fix this but I just want to make sure it's allowed under v1.4

**Comment by salty-flower** [comment]
I would consider this as fixing bugs🤔

**Comment by salty-flower** [comment]
Ono...
> Q6: Can we tweak error/help messages (or other text shown to the user)?
> A: Only if the current text is incorrect (i.e., a bug). Adding more information or otherwise 'enhancing' the text is not allowed.

**Comment by vsamarth** [comment]
Then I am closing it since we can not fix it in this release.
